In [5]:
#ndarray 개요
import numpy as np

In [6]:
#Indexing
array1 = np.arange(start=1,stop=10)
print("array1 : ",array1) #1차원 ndarray가 9개

array1 :  [1 2 3 4 5 6 7 8 9]


In [49]:
#단일값
print("3번째 Index : array1[2] =",array1[2])
print("맨 뒤 Index : array1[-1] =",array1[-1])
print("* 단일값 type : ",type(array1[1]))

3번째 Index : array1[2] = 3
맨 뒤 Index : array1[-1] = 9
* 단일값 type :  <class 'numpy.int32'>


In [17]:
#++차원변환++
array1d = array1.reshape(3,3)
print("3X3차원 : \n",array1d)
print("row=0,col=0 index =",array1d[0,0])
print("row=1,col=2 index =",array1d[1,2])
print("row=2,col=2 index =",array1d[2,2])

3X3차원 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
row=0,col=0 index = 1
row=1,col=2 index = 6
row=2,col=2 index =  9


In [48]:
#슬라이싱
print("인덱스 0~3 : array1[:3] =",array1[:3])
print("인덱스 3~ : array1[3:] =",array1[3:])
print("인덱스 처음~끝 : array[:] =",array1[:])
print("* 슬라이싱 type :",type(array1[:3]))

인덱스 0~3 : array1[:3] = [1 2 3]
인덱스 3~ : array1[3:] = [4 5 6 7 8 9]
인덱스 처음~끝 : array[:] = [1 2 3 4 5 6 7 8 9]
* 슬라이싱 type : <class 'numpy.ndarray'>


In [47]:
#펜시 인덱싱 Fancy Indexing
array2 = array1.reshape(3,3) #3X3으로 차원변환
print("* 기본 :\n",array2)
print("펜시 인덱싱 array2[[0,1],2] =",array2[[0,1],2].tolist())
print("펜시 인덱싱 array2[[0,1],0:2] =",array2[[0,1],0:2].tolist())
print("펜시 인덱싱 array2[0,1] =",array2[[0,1]].tolist())

* 기본 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
펜시 인덱싱 array2[[0,1],2] = [3, 6]
펜시 인덱싱 array2[[0,1],0:2] = [[1, 2], [4, 5]]
펜시 인덱싱 array2[0,1] = [[1, 2, 3], [4, 5, 6]]


In [46]:
#불린 인덱싱 Boolean indexing
print("불린 인덱싱 array1 > 5 :",array1[array1>5])
array3 = array1 > 5
print("조건 할당 :",array3)
print(">> array1에 인덱스 필터링 :",array1[array3])
print(">> 값 일치?",array1[array1>5]==array1[array3])

불린 인덱싱 array1 > 5 : [6 7 8 9]
조건 할당 : [False False False False False  True  True  True  True]
>> array1에 인덱스 필터링 : [6 7 8 9]
>> 값 일치? [ True  True  True  True]
