# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
z = np.zeros(10)
np.size(z)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
# z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
print(a[::-1])

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
b = np.arange(9)
print(b.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
c = np.array([1,2,0,0,4,0])
d = np.nonzero(c)
print(d)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
e = np.identity(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.rand(3,3,3)

array([[[0.32357681, 0.09203646, 0.54600412],
        [0.31729172, 0.40109905, 0.61098294],
        [0.59303643, 0.95760828, 0.29783076]],

       [[0.87912428, 0.4797419 , 0.98348132],
        [0.12018362, 0.94526953, 0.84312187],
        [0.0314632 , 0.71242356, 0.151801  ]],

       [[0.67704946, 0.99798136, 0.27810823],
        [0.12899302, 0.15453336, 0.39692002],
        [0.65374576, 0.28985788, 0.06479252]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
f = np.random.rand(10,10)
print(f)
print("min =",np.min(f))
print("max =",np.max(f))

[[0.39164644 0.11536148 0.08931543 0.54855093 0.72570068 0.63750861
  0.3190354  0.43561059 0.62602192 0.31009223]
 [0.67591183 0.11536967 0.22162465 0.96331448 0.79330549 0.21756545
  0.53925583 0.59234896 0.29617778 0.97727257]
 [0.02730858 0.78159098 0.16007225 0.33623928 0.95437614 0.81375353
  0.72953682 0.6221224  0.65386574 0.60418317]
 [0.90857035 0.65428238 0.56884452 0.66172516 0.67151557 0.834301
  0.36164681 0.55113688 0.77659457 0.62714052]
 [0.71180017 0.52177857 0.66650558 0.30930415 0.77795297 0.96394031
  0.34587247 0.43968511 0.73778398 0.81355343]
 [0.18015926 0.42701257 0.73221584 0.9287807  0.71382589 0.24946319
  0.93903332 0.61352903 0.49612316 0.64404613]
 [0.29636899 0.20875625 0.2750512  0.75862562 0.27243714 0.41499358
  0.34396929 0.46811629 0.73989487 0.45624837]
 [0.20393961 0.05074646 0.20098539 0.44883323 0.82623142 0.47409168
  0.01670771 0.75528457 0.83138111 0.41662199]
 [0.61644614 0.60850685 0.68778923 0.02047766 0.95033045 0.22147272
  0.08710109 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
g = np.random.random(30)
print(g)
print("mean =",np.mean(g))

[0.22765265 0.80879069 0.02280897 0.17560769 0.83219732 0.22415069
 0.21210676 0.50160768 0.37983161 0.96414778 0.96498835 0.80121677
 0.05738755 0.7703686  0.06172769 0.81442516 0.65281925 0.7421511
 0.89922479 0.56619624 0.6087787  0.41454584 0.39522836 0.69406684
 0.60727435 0.88812243 0.89727735 0.54012189 0.5770033  0.93396034]
mean = 0.5745262242282817


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
array2d = np.ones([5,5])
print(array2d)

array2d[1:-1,1:-1]=0
print("\n",array2d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
h = np.ones((5,5))
h = np.pad(h, pad_width=1, mode='constant', constant_values=0)
print(h)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
Y = np.diag(1+np.arange(4)) # = np,diag([1,2,3,4])
print("4x4 =\n",Y)

Z = np.diag(1+np.arange(4),k=-1)
print("5x5 =\n",Z)

4x4 =
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
5x5 =
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
#모르겠음

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4)) #[0,1]과 [1,0] array를 4번*4번 반복
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.39896731 -0.23447114  1.50823939  0.13143743  1.46081257]
 [-1.17162218  1.20736625  0.17416385  1.432903   -0.24148248]
 [-1.71481394  0.50474559 -1.67428347  0.1636585  -0.9638158 ]
 [ 0.06046587 -0.55436984  0.07241251 -1.74591769  0.20000148]
 [ 0.12172948  1.56513696  1.01972511 -1.00806031 -0.71292844]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
#모르겠음

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.arange(11) # 0~10
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

# Z**Z illegal

ValueError: Integers to negative integer powers are not allowed.

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

# array간 나누는 건 불가능 하지만 몫을 구하는 건 가능

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,10,10)
np.copysign(np.ceil(np.abs(Z)),Z) #abs로 절대값, ceil로 올림

[-9. -4.  9. -7.  7. -8. -5.  4. -6. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
A = np.random.randint(0,10,10)
B = np.random.randint(0,10,10)
print("A =",A,"\nB =",B)
np.intersect1d(A,B)

A = [9 0 3 4 9 5 6 7 6 2] 
B = [3 9 8 8 9 4 9 6 8 6]


array([3, 4, 6, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#모르겠음

defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(1) == np.emath.sqrt(1))

False
True


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print(yesterday)
print(today)
print(tomorrow)

2021-09-16
2021-09-17
2021-09-18


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
print("A",A)
print("B",B)
np.add(A,B,out=B) #B에 A와 B추가한 값 부여
np.divide(A,2,out=A) #A 나누기 2
np.negative(A,out=A) #A를 음수로
print(np.multiply(A,B,out=A))  #A와 B 곱함

A [1. 1. 1.]
B [2. 2. 2.]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1) #Z에서 Z를1로 나눈 나머지를 뺀 정수부분
print(np.floor(Z)) #내림
print(np.ceil(Z)) #올림
print(Z.astype(int)) #integer변환
print(np.trunc(Z))#input에서 소수점 제외

[3. 0. 7. 8. 5. 6. 9. 5. 5. 7.]
[3. 0. 7. 8. 5. 6. 9. 5. 5. 7.]
[ 4.  1.  8.  9.  6.  7. 10.  6.  6.  8.]
[3 0 7 8 5 6 9 5 5 7]
[3. 0. 7. 8. 5. 6. 9. 5. 5. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5) # 0~4
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:] #0과 1을 포함하는 11개 값
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.22140996 0.31438848 0.34749214 0.40933401 0.41405743 0.64597434
 0.74054394 0.74828959 0.80759021 0.9963488 ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
 A = np.random.randint(0,2,5)
 B = np.random.randint(0,2,5)

 print(np.allclose(A,B))
 print(np.array_equal(A,B))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1
#writeable을 false로 하여 read-only결과값만

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.random((10,2))
X = Z[:,0]
Y = Z[:,1]

R = np.sqrt(X**2 + Y**2)
print("R =",R)

P = np.arctan(Y,X)
print("P =",P)

[0.69678553 0.55447005 0.69147956 0.65308354 1.03335567 0.819672
 1.14272421 0.24083072 0.57057543 0.96377523]
[0.56186664 0.48794703 0.29892836 0.00675794 0.78334877 0.55270817
 0.54175506 0.16223284 0.45073744 0.49682923]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.30478994 0.         0.66964602 0.79002862 0.6651047  0.47454544
 0.41449126 0.30050587 0.19449958 0.64293247]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
#모르겠음

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros(16, 16)
print(Z)

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.random.randint(0,10,10)
print(Z)
Z[Z.argmin()]

[4 3 1 6 9 0 3 2 0 6]


0

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10,[('position',[('x',float,1),('y',float,1),('z',float,1)]),
                 ('color',[('x',float,1),('g',float,1),('b',float,1)])])
print(Z)

[((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))
 ((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))
 ((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))
 ((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))
 ((0., 0., 0.), (0., 0., 0.)) ((0., 0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2, (Y-Y.T)**2)
print(D)

[[0.         0.19346729 0.25686713 0.45123643 0.4231096  0.04963241
  0.36047311 0.68423223 0.17691629 0.0993225 ]
 [0.19346729 0.         0.45033441 0.64470371 0.61657688 0.2430997
  0.5539404  0.87769951 0.016551   0.09414479]
 [0.25686713 0.45033441 0.         0.1943693  0.16624247 0.20723472
  0.10360599 0.4273651  0.43378341 0.35618963]
 [0.45123643 0.64470371 0.1943693  0.         0.02812683 0.40160402
  0.09076331 0.2329958  0.62815272 0.55055893]
 [0.4231096  0.61657688 0.16624247 0.02812683 0.         0.37347719
  0.06263648 0.26112263 0.60002588 0.5224321 ]
 [0.04963241 0.2430997  0.20723472 0.40160402 0.37347719 0.
  0.3108407  0.63459982 0.2265487  0.14895491]
 [0.36047311 0.5539404  0.10360599 0.09076331 0.06263648 0.3108407
  0.         0.32375911 0.5373894  0.45979561]
 [0.68423223 0.87769951 0.4273651  0.2329958  0.26112263 0.63459982
  0.32375911 0.         0.86114852 0.78355473]
 [0.17691629 0.016551   0.43378341 0.62815272 0.60002588 0.2265487
  0.5373894  0.86114852

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32,copy=False)
print(Z)
print(type(Z))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [6]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [7]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
    
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X,Y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)

sigma = 1
mu = 0

G = np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [8]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [10]:
X = np.random.rand(5,10)
Y = X - X.mean(axis=1,keepdims=True) #차원유지 상태로 dimension 유지
print(Y)

[[ 0.37531767 -0.53351077 -0.11744404  0.34182457  0.10555153 -0.51011229
  -0.42937754 -0.00649801  0.36089576  0.41335312]
 [ 0.1398563  -0.37079904 -0.08266515  0.44330121 -0.23056981  0.0842492
  -0.01195354  0.35716128 -0.37543154  0.04685109]
 [-0.12766742  0.00612903 -0.08408429  0.25567183  0.13912241 -0.0978752
   0.3829682  -0.17143924 -0.28425411 -0.01857121]
 [ 0.48680367 -0.18518855 -0.24180444 -0.15937993  0.25271054 -0.04951544
  -0.13985465  0.33357088 -0.293077   -0.00426509]
 [ 0.1453366  -0.23312482 -0.10778261  0.04616087  0.06259326  0.5108518
  -0.43156071 -0.14035989  0.06498119  0.08290431]]


#### 59. How to sort an array by the nth column? (★★☆)

In [14]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print("sort : \n",Z[Z[:,1].argsort()]) #행의 첫번째 숫자로

[[6 3 0]
 [7 4 9]
 [3 9 8]]
sort : 
 [[6 3 0]
 [7 4 9]
 [3 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [16]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any()) #null인 column이 있는지 확인

[[1 0 0 0 0 2 1 1 1 1]
 [0 1 0 2 2 0 0 1 1 2]
 [1 2 0 0 0 1 2 0 0 0]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [17]:
Z = np.random.uniform(0,1,10)
z = 0.5 
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

0.49389906845519793


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [18]:
#모르겠음

A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [20]:
#모르겠음

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [21]:
Z = np.ones(10)
a = np.random.randint(0,len(Z),20)
np.add.at(Z,a,1)
print(a)
print(Z)

[1 2 8 3 6 2 4 7 9 8 6 6 0 1 7 2 5 6 4 0]
[3. 3. 4. 2. 3. 2. 5. 3. 3. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [22]:
X = [1,2,3,4,5,6]
I = [3,4,5,6,7,8] #index라서 3번째부터 x원소
F = np.bincount(I,X)
print(F)

[0. 0. 0. 1. 2. 3. 4. 5. 6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [24]:
#모르겠음

img = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = img[...,0]*(256*256) + img[...,1]*256 + img[...,2]
print(len(np.unique(F)))

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)